

#配置负载均衡的的调用
product-service:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    OkToRetryOnAllOperations: true #是否对所有的操作重试
    MaxAutoRetriesNextServer: 2    #切换实例的重试次数

#配置熔断
feign:
  hystrix:
    enabled: true

#暴露所有健康监控节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
#添加RabbitMQ的配置
spring:
  rabbitmq:
    host: 120.27.144.231
    virtual-host: /1907
    username: java1907
    password: 123
